### PR TITLE
Add cross-media-measuerment repo boilerplate

### PR DESCRIPTION
**Pull request by corbantek**
Add the default cross-media-measurement repo boiler plate template

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2)

### CODE REVIEW

**Review by corbantek — COMMENTED** [review]
As requested.  Once this is merged I'll rebase my other commit on top of this one.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2#-:-Mbqav118DCC6j2Tx5Rx:b-kze530)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @kungfucraig, @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig, @SanjayVas, @wangyaopw, and @zachcwc)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @kungfucraig, @wangyaopw, and @zachcwc)

___
*[.github/workflows/build-test.yml, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2#-MbqzwqD8NXisHvZja1N:-MbqzwqE8NjZnr5ts0Jk:buiix4f) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/917f8b27d2c64bb02beaf31913162b8482002ecd/.github/workflows/build-test.yml#L34)):*
> ```
> v1.3.0
> ```
nit: use the new floating v1 release, which we'll continue to update until we have a breaking change that necessitates a new major version.
___
*[.github/workflows/lint.yml, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2#-Mbr-8R-6-2WR9zsMmAU:-Mbr-8R-6-2WR9zsMmAV:bg0n4ln) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/917f8b27d2c64bb02beaf31913162b8482002ecd/.github/workflows/lint.yml#L29)):*
> ```
> v1.3.0
> ```
Same in this file re: floating v1 release for our WFA actions.

**Review by corbantek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[.github/workflows/build-test.yml, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2#-MbqzwqD8NXisHvZja1N:-Mbr5S_M5wXqq2nsOVzD:bcj5mov) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/917f8b27d2c64bb02beaf31913162b8482002ecd/.github/workflows/build-test.yml#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> v1.3.0
> ```
nit: use the new floating v1 release, which we'll continue to update until we have a breaking change that necessitates a new major version.
</blockquote></details>

Will update in other PR
___
*[.github/workflows/lint.yml, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/2#-Mbr-8R-6-2WR9zsMmAU:-Mbr5VqE2fIkRUAxEfgX:b-z4unpf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/917f8b27d2c64bb02beaf31913162b8482002ecd/.github/workflows/lint.yml#L29)):*
> Will update in other PR

**Pull request merged**
