### PR TITLE
Add a createDataProviderListHash method.

### PR DESCRIPTION
**Pull request by wangyaopw**
Also updated the hashsha256(data,salt) to put the salt at the end of the
data.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @corbantek)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-Mgm7lCj3yhF8kOF9DE7:-Mgm7lCj3yhF8kOF9DE8:brgl3mu) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4602c08c5c7de329f9b3d9eb3bdc9da1ec563bc2/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L72)):*
> ```Kotlin
>       .decode(
>         "MEYCIQDYsRraa6oDpIsLNvAX99YbOiHOIHOXBmdikoy6OS4x6gIhANRmCKtoUD3zjGxwv/7ddl0WJ" +
>           "Dj1Pj22VkWFVFBOlrgs"
> ```

I got this string from the DataProviderClientTest. It is the generated signature in the test. However, the `duchy verifies edp participation signature` fails in the DuchyClientTest. 

@corbantek How did you get the original string?

**Review by corbantek — COMMENTED** [review]
Is there a benefit for putting the salt at the end?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-:-MgmERwW50rQsJT5aEz3:bfbztsk)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by wangyaopw — COMMENTED** [review]
salt is added to the end of the data is the convention I guess. Also in our documentation of the hash, we say it is `SHA256 hash of the concatenation of serialized_data_provider_list and data_provider_list_salt`

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-:-MgmJheU4FiFX6Eo9WuY:b-sabt8x)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by corbantek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-Mgm7lCj3yhF8kOF9DE7:-Mgql0rY9cvk_R8hVnxW:br7uva9) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4602c08c5c7de329f9b3d9eb3bdc9da1ec563bc2/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L72)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I got this string from the DataProviderClientTest. It is the generated signature in the test. However, the `duchy verifies edp participation signature` fails in the DuchyClientTest. 

@corbantek How did you get the original string?
</blockquote></details>

Try this signature: (it should work with your changes)
`"MEUCIQDPd2A85kgBbOGyeeNGlzcRO+uLK6qT9TkHSUDcejHu1wIgGv2YA4xAME8nZrjSbjOu5CTi/ilgis7bMXA5iSgSdRE="`

But the real issue is you have to use 
```kotlin
import org.wfanet.measurement.common.crypto.testing.FIXED_SERVER_CERT_PEM_FILE as EDP_1_CERT_PEM_FILE
import org.wfanet.measurement.common.crypto.testing.FIXED_SERVER_KEY_FILE as EDP_1_KEY_FILE
```
when generating the Signature in `duchy verifies edp participation signature`

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @corbantek and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-Mgm7lCj3yhF8kOF9DE7:-MgqqPhvEbvi-cQFYdUl:b9m9bzp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4602c08c5c7de329f9b3d9eb3bdc9da1ec563bc2/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L72)):*
> MEUCIQDPd2A85kgBbOGyeeNGlzcRO+uLK6qT9TkHSUDcejHu1wIgGv2YA4xAME8nZrjSbjOu5CTi/ilgis7bMXA5iSgSdRE=
Thanks for catching this.

I updated the tests to both use `org.wfanet.measurement.consent.testing.org.wfanet.measurement.consent.testing.`

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @corbantek and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-Mgm7lCj3yhF8kOF9DE7:-MgqsByP8wmSofgC0QRR:b4a0wzn) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4602c08c5c7de329f9b3d9eb3bdc9da1ec563bc2/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L72)):*
> MEUCIQDPd2A85kgBbOGyeeNGlzcRO+uLK6qT9TkHSUDcejHu1wIgGv2YA4xAME8nZrjSbjOu5CTi/ilgis7bMXA5iSgSdRE=
oh, yep. I was wondering why the tests passed locally but failed in the github action.

Thanks

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @corbantek, @SanjayVas, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-Mgm7lCj3yhF8kOF9DE7:-Mgqszd6BPm9LnC8Of7Y:b-szd93z) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4602c08c5c7de329f9b3d9eb3bdc9da1ec563bc2/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L72)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> MEUCIQDPd2A85kgBbOGyeeNGlzcRO+uLK6qT9TkHSUDcejHu1wIgGv2YA4xAME8nZrjSbjOu5CTi/ilgis7bMXA5iSgSdRE=
oh, yep. I was wondering why the tests passed locally but failed in the github action.

Thanks
</blockquote></details>

Somehow the UI messed up my message. re-posting

oh, yep. I was wondering why the tests passed locally but failed in the github action. Thanks

**Review by corbantek — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-:-MgquJ7P0RnqIXKe0X0-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-Mgr7a0C3oNj-wImIumW:-Mgr7a0C3oNj-wImIumX:bu97mh4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f326e960ebbdb2e6150a38d8535e277f4d4cdc4/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L32)):*
> ```
> `dataProviderList`
> ```
nit: use KDoc references rather than code formatting
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-Mgr7oPHDhOeKdCtgxDx:-Mgr7oPHDhOeKdCtgxDy:brvgkrh) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f326e960ebbdb2e6150a38d8535e277f4d4cdc4/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L116)):*
> ```Kotlin
>     val dataProviderListSalt = ByteString.copyFromUtf8("salt")
>     val concatenation = dataProviderList.concat(dataProviderListSalt)
>     assertEquals(
> ```

Use Truth rather than `assertEquals`

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @corbantek, @SanjayVas, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-Mgr7oPHDhOeKdCtgxDx:-MgrA-nvCiTz_0HUqOVC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f326e960ebbdb2e6150a38d8535e277f4d4cdc4/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L116)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Truth rather than `assertEquals`
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-MgrRMRU7kGZNbBsRKOY:-MgrRMRU7kGZNbBsRKOZ:b-wsuj5s) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eca3bae72a22926ff65c25f260ea9fc31e45938e/src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt#L25)):*
> ```Kotlin
> fun hashSha256(data: ByteString, salt: ByteString): ByteString {
>   val sha256MessageDigest = MessageDigest.getInstance(HASH_ALGORITHM)
>   sha256MessageDigest.update(data.toByteArray())
> ```

The examples I see on the Internet show the original as being correct. What documentation are you looking at?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-MgrRMRU7kGZNbBsRKOY:-MgrSwaR0TIKHOWL8NGv:bqtgo5t) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eca3bae72a22926ff65c25f260ea9fc31e45938e/src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

The examples I see on the Internet show the original as being correct. What documentation are you looking at?
</blockquote></details>

salt can be added either to the front or the end of the data. The example in wiki puts it at the end. https://en.wikipedia.org/wiki/Salt_(cryptography)

But most importantly, the comment in our public api proto says it is the hash of the concatenation of DataProviderList and DataProviderListSalt. so at least our implementation needs to match the comment.

https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L91

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by corbantek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @corbantek and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt, line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13#-MgrRMRU7kGZNbBsRKOY:-MgvHMc-B34_RrlRIKHR:b-idlxea) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eca3bae72a22926ff65c25f260ea9fc31e45938e/src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

still not sure if thats the right way to do it... However, please add a comment why you're doing it this way. Should we change the documentation @sanjayvas 
</blockquote></details>

I added to the comment that we are adding salt to the end of the data.

But the comment doesn't say why we do it in this way. It is just a choice, no matter salt+data or data+salt, or some crazy permutation between them.

@SanjayVas is out until next Tuesday. I am pretty sure he agrees with the change, since he asked me to do it in the PR. I only need the method I added in the PR to call and don't really care about how the hash is computed.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @corbantek and @SanjayVas)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
