### PR TITLE
Update the common-jvm version.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel, line 14 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18#-Mj0hlIl-09sCiNEheWO:-Mj0hlIl-09sCiNEheWP:bqv7836) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/bdc5913e471d40a9b1a2e499b1192ee267bfb654/src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel#L14)):*
> ```
> common_name = "some-mc-1.example.com",
> ```
The common name should actually *not* be DNS hostname. The `hostname` field maps to subject alternative name, which replaced common name as the X.509 field for a DNS hostname.
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18#-Mj0i0ig2D6x6LN-9Qc7:-Mj0i0ig2D6x6LN-9Qc8:b-pja6pc) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/bdc5913e471d40a9b1a2e499b1192ee267bfb654/src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel#L15)):*
> ```
> hostname = "localhost",
> ```
nit: Use some realistic DNS hostname, e.g. what we have for common_name right now.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel, line 14 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18#-Mj0hlIl-09sCiNEheWO:-Mj0jYLv-40TsEBDC30U:b-7tdf7d) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/bdc5913e471d40a9b1a2e499b1192ee267bfb654/src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> common_name = "some-mc-1.example.com",
> ```
The common name should actually *not* be DNS hostname. The `hostname` field maps to subject alternative name, which replaced common name as the X.509 field for a DNS hostname.
</blockquote></details>

agree
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18#-Mj0i0ig2D6x6LN-9Qc7:-Mj0jZHU9OocaoSajjzq:b-7tdf7d) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/bdc5913e471d40a9b1a2e499b1192ee267bfb654/src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> hostname = "localhost",
> ```
nit: Use some realistic DNS hostname, e.g. what we have for common_name right now.
</blockquote></details>

agree

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @corbantek and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel, line 14 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18#-Mj0hlIl-09sCiNEheWO:-Mj0m1KWE56G-hZfbK1t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/bdc5913e471d40a9b1a2e499b1192ee267bfb654/src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel#L14)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18#-Mj0i0ig2D6x6LN-9Qc7:-Mj0m25i2rU8ls65z-yP:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/bdc5913e471d40a9b1a2e499b1192ee267bfb654/src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Done

**Review by corbantek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18#-:-Mj0s7LYErsOiFHMlU7k:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
