### PR TITLE
Implement Tink Hybrid Encryption and Aead (KMS) Store

### PR DESCRIPTION
**Pull request by corbantek**
- Incorporating recent changes of EncryptionPublicKey and removal of HybridCipherSuite
  - EciesCryptor is no longer needed (nor the mapper) and we can call encrypt and decrypt directly from the PrivateKeyHandle and PublicKeyHandle interfaces
  - Under the covers we actually implement those interfaces by wrapping Tink
  - PublicKeyHandle provides a factory to convert a EncryptionPublicKey to a PublicKeyHandle
- Aead and TinkAead wrap the Head interface (encrypt/decrypt) of Tink
- AeadStore is an implementation of Store that will encrypt before writing a blob and decrypt when returning a blob (read)
  - Note: Inorder to implement AeadStore, the store/get methods need to marked “open”
- AeadPrivateKeyStore is a specific implementation of AeadStore that deals with storing PrivateKey (currently only ECIES keys)
- Signing can also be performed by the PrivateKeyHandle (using Think as its implementation)

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25)

### CODE REVIEW

**Review by corbantek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25)* status: 0 of 36 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlG3te4Evet3Y7I8OLH:-MlG3te4Evet3Y7I8OLI:b398r8f) (no related file):*
I wanted people to have some eyes on this before its complete as its a lot of refactoring based on recent changes.

Current TODOS:
- Waiting on https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/44 to implement AeadStore
- Fix all tests
- Spruce up some of the Signature Verify stuff

---

**Review by corbantek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25)* status: 0 of 36 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/AeadStore.kt, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGImgl6pFUBMOc3Fvv:-MlGImgl6pFUBMOc3Fvw:bnt4v6r) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/AeadStore.kt#L16)):*
> ```Kotlin
> private const val BLOB_KEY_PREFIX = "/aead"
> 
> class AeadStore
> ```

After the discussion in the Measurement Meeting, I think it actually might make sense to make this class `abstract` so it's like the current `Store` but with aead encryption by default under the covers.  This would allow the developer to keep the "blob folder" property that Store creates (as here I'm hardcoding everything to `"/aead"`which is not correct). 

I'll make this change asap, however Store.write/get still need to be marked `open`

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 24 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25)* status: 24 of 36 files reviewed, 9 unresolved discussions (waiting on @corbantek, @duliomatos1, @efoxepstein, @SanjayVas, and @wangyaopw)

___
*[WORKSPACE, line 166 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGZ_O4CjT3JOYiL3jM:-MlGZ_O4CjT3JOYiL3jN:bqgj63n) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/WORKSPACE#L166)):*
> ```Starlark
> 
> # Measurement proto.
> # Common JVM for Measurement
> ```

whats this comment for?
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/TinkAead.kt, line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlG_NXu2tCO2W6NxjXe:-MlG_NXu2tCO2W6NxjXf:b-91j8rr) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/TinkAead.kt#L10)):*
> ```Kotlin
> 
>   override fun encrypt(data: ByteString): ByteString {
>     return ByteString.copyFrom(aead.encrypt(data.toByteArray(), byteArrayOf()))
> ```

is there associated data we want to include here?
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/TinkPublicKeyHandle.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlG_syHAXqC5TrWO6yc:-MlG_syHAXqC5TrWO6yd:bal8713) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/TinkPublicKeyHandle.kt#L26)):*
> ```Kotlin
>       verifier.verify(signature.toByteArray(), data.toByteArray())
>     } catch (e: GeneralSecurityException) {
>       return false
> ```

probably should log this error
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/TinkPublicKeyHandle.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGa-aT6b_JgdxcUjVT:-MlGa-aT6b_JgdxcUjVU:bywnvac) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/TinkPublicKeyHandle.kt#L37)):*
> ```Kotlin
>       BinaryKeysetWriter.withOutputStream(publicKeyByteArrayOutputStream)
>     )
>     return EncryptionPublicKey.newBuilder()
> ```

```
return encryptionPublicKey {
        format = EncryptionPublicKey.Format.TINK_KEYSET // TODO - Update to TINK_KEYSET
        data = ByteString.copyFrom(publicKeyByteArrayOutputStream.toByteArray())
}

```
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/testing/TinkDerKeysetReader.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGaJxd7GqRKHUQeTFg:-MlGaJxd7GqRKHUQeTFh:bhl1jj2) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/testing/TinkDerKeysetReader.kt#L82)):*
> ```Kotlin
>       }
>     val key =
>       Keyset.Key.newBuilder()
> ```

Use the Kotlin DSL `key {...}` 
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/testing/TinkDerKeysetReader.kt, line 161 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGaYicEce4zWPhqcAp:-MlGaYicEce4zWPhqcAq:b-427et0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/testing/TinkDerKeysetReader.kt#L161)):*
> ```Kotlin
>           hkdfHashType = getHashType(pemKeyType)
>           curveType = getCurveType(pemKeyType)
>           // hkdfSalt = KEJ - Should we be setting a Salt??
> ```

i believe we have salts for this sometimes, right? maybe maybe it an optional param
___
*[src/test/kotlin/org/wfanet/measurement/consent/crypto/testing/BUILD.bazel, line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGajJiBPoc68TMIdXp:-MlGajJiBPoc68TMIdXq:b-6uea1e) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/test/kotlin/org/wfanet/measurement/consent/crypto/testing/BUILD.bazel#L9)):*
> ```Starlark
>     deps = [
>         "//src/main/kotlin/org/wfanet/measurement/consent/crypto:utils",
>         "
> ```

looks like a stray quote

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25)* status: 27 of 36 files reviewed, 13 unresolved discussions (waiting on @corbantek, @duliomatos1, @efoxepstein, @stevenwarejones, and @wangyaopw)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGZmOa0AIbsCHqpke1):*

I'm assuming you intend for this to be the body of the merge message, so commenting accordingly.

> Aead and TinkAead wrap the Head interface (encrypt/decrypt) of Tink

"Head" -> `Aead`? 

> Note: Inorder to implement AeadStore, the store/get methods need to marked “open”

"Inorder" -> "In order". Probably want to reference world-federation-of-advertisers/common-jvm#44.

> Signing can also be performed by the PrivateKeyHandle (using Think as its implementation)

"Think" -> "Tink"
___
*[WORKSPACE, line 166 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGZtp92zmNP00Fq0SZ:-MlGZtp92zmNP00Fq0S_:b-8mspcm) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/WORKSPACE#L166)):*
> ```
> # Common JVM for Measurement
> ```
???
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Aead.kt, line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlG_B79B3W0rnXNkBzB:-MlG_B79B3W0rnXNkBzC:bfu5ttw) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/Aead.kt#L9)):*
> ```
> encryptedData
> ```
This is fine, but note that the common term for this is "ciphertext" with the opposite being "plaintext"
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/AeadStore.kt, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGImgl6pFUBMOc3Fvv:-MlG_lqJ3bo3Y0Ko3L0M:biv6z94) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/AeadStore.kt#L16)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

After the discussion in the Measurement Meeting, I think it actually might make sense to make this class `abstract` so it's like the current `Store` but with aead encryption by default under the covers.  This would allow the developer to keep the "blob folder" property that Store creates (as here I'm hardcoding everything to `"/aead"`which is not correct). 

I'll make this change asap, however Store.write/get still need to be marked `open`
</blockquote></details>

The `Store` implementation provides the following: the private blob key prefix, the context type, and a public blob key generator for that context.

`AeadStore` provides encryption on write and decryption on read, and `AeadPrivateKeyStore` wraps an `AeadStore` to deal with handles instead of `ByteString`s. These are different abstractions in the current implementation, as the first extends `Store` and the latter wraps it. I feel like you'd want the same abstraction for both.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/AeadPrivateKeyStore.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGcEk249y5LoR09BEi:-MlGcEk249y5LoR09BEj:b-8h1wgk) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/AeadPrivateKeyStore.kt#L23)):*
> ```
>      * Tink does not provide a way to separate the aead encryption and writing of the key. To
>      * workaround this we are using CleartextKeysetHandle which calls the unencrypted write method,
> ```
Rather than work around this, I think it would be better to use a design that still can use it. There's no need for AeadPrivateKeyStore to wrap an AeadStore. My assumption was in fact that these would be parallel implementations: the former using Tink's normal reader/writer API to encrypt/decrypt keysets, and the latter calling Aead directly.

**Review by corbantek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25)* status: 27 of 36 files reviewed, 13 unresolved discussions (waiting on @corbantek, @duliomatos1, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGZmOa0AIbsCHqpke1):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>


I'm assuming you intend for this to be the body of the merge message, so commenting accordingly.

> Aead and TinkAead wrap the Head interface (encrypt/decrypt) of Tink

"Head" -> `Aead`? 

> Note: Inorder to implement AeadStore, the store/get methods need to marked “open”

"Inorder" -> "In order". Probably want to reference world-federation-of-advertisers/common-jvm#44.

> Signing can also be performed by the PrivateKeyHandle (using Think as its implementation)

"Think" -> "Tink"
</blockquote></details>

Will fix, for some reason my editor was on insane spell fix....
___
*[WORKSPACE, line 166 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGZtp92zmNP00Fq0SZ:-MlGe8Bb3roNc30XFZF0:b-ckcf67) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/WORKSPACE#L166)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> # Common JVM for Measurement
> ```
???
</blockquote></details>

Accidental rebase error, will remove
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Aead.kt, line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlG_B79B3W0rnXNkBzB:-MlGeL5QBfRHFzeY_tqM:b-nebnsw) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/Aead.kt#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> encryptedData
> ```
This is fine, but note that the common term for this is "ciphertext" with the opposite being "plaintext"
</blockquote></details>

will update globally in consent-signalling
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/AeadStore.kt, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGImgl6pFUBMOc3Fvv:-MlGeh2YD6Aqaq-M_hwC:b-xlyppz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/AeadStore.kt#L16)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The `Store` implementation provides the following: the private blob key prefix, the context type, and a public blob key generator for that context.

`AeadStore` provides encryption on write and decryption on read, and `AeadPrivateKeyStore` wraps an `AeadStore` to deal with handles instead of `ByteString`s. These are different abstractions in the current implementation, as the first extends `Store` and the latter wraps it. I feel like you'd want the same abstraction for both.
</blockquote></details>

I guess I wasn't clear, was going to have AeadStore extend Store, and AeadPrivateKeyStore extend AeadStore instead of the current wrapping of AeadStore
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/TinkAead.kt, line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlG_NXu2tCO2W6NxjXe:-MlGf-C80i-7OEFxmM_Z:b7rekla) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/TinkAead.kt#L10)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is there associated data we want to include here?
</blockquote></details>

Currently we don't but I can expose that argument if its helpful
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/AeadPrivateKeyStore.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGcEk249y5LoR09BEi:-MlGfD7d4znWo3-8dLf1:biggjik) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/AeadPrivateKeyStore.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>      * Tink does not provide a way to separate the aead encryption and writing of the key. To
>      * workaround this we are using CleartextKeysetHandle which calls the unencrypted write method,
> ```
Rather than work around this, I think it would be better to use a design that still can use it. There's no need for AeadPrivateKeyStore to wrap an AeadStore. My assumption was in fact that these would be parallel implementations: the former using Tink's normal reader/writer API to encrypt/decrypt keysets, and the latter calling Aead directly.
</blockquote></details>

I think my issue when I tired to do this was no exposing the tink.Aead directly in our code, since Tink requires that.  

I guess a work around is I could have our consent Aead implement the tink Aead interface and that would allow me to pass it back into Tink.  

Your suggestion was my original implementation and broke when I wrapped Aead, but thinking it through I think I can make this work without exposing Tink at this level.

Will update tonight
___
*[src/test/kotlin/org/wfanet/measurement/consent/crypto/testing/BUILD.bazel, line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGajJiBPoc68TMIdXp:-MlGgFTY1VZUD9WwQjbJ:bvr1g4p) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/test/kotlin/org/wfanet/measurement/consent/crypto/testing/BUILD.bazel#L9)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

looks like a stray quote
</blockquote></details>

Thanks, will fix

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25)* status: 27 of 36 files reviewed, 12 unresolved discussions (waiting on @corbantek, @duliomatos1, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/AeadStore.kt, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGImgl6pFUBMOc3Fvv:-MlGkNZk6RQ2H1200OMO:b-it7wko) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/AeadStore.kt#L16)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

I guess I wasn't clear, was going to have AeadStore extend Store, and AeadPrivateKeyStore extend AeadStore instead of the current wrapping of AeadStore
</blockquote></details>

That would mean that `AeadPrivateKeyStore` extends `Store` and exposes reading/writing of `ByteString`s?
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/AeadPrivateKeyStore.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/25#-MlGcEk249y5LoR09BEi:-MlGkoXNB2EMMjSggbXq:bfoai9) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f38944ee84a025b201f25a90e5b1df0ca2db6599/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/AeadPrivateKeyStore.kt#L23)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

I think my issue when I tired to do this was no exposing the tink.Aead directly in our code, since Tink requires that.  

I guess a work around is I could have our consent Aead implement the tink Aead interface and that would allow me to pass it back into Tink.  

Your suggestion was my original implementation and broke when I wrapped Aead, but thinking it through I think I can make this work without exposing Tink at this level.

Will update tonight
</blockquote></details>

Note that only the public interfaces need to encapsulate Tink. Implementations can be Tink-specific. There should be a single entry-point for the entire crypto library that determines whether you get Tink implementations. e.g. a class with factory methods that return implementations of the public interfaces you need.

Therefore, the Tink PrivateKeyStore impl can take in a Tink Aead instance in its constructor.

**Comment by corbantek** [comment]
Abandoning for work being done in common-jvm crypto
Latest https://github.com/world-federation-of-advertisers/common-jvm/pull/49

**Pull request closed without merging**
