### PR TITLE
Update common-jvm to 0.20.1, using hashing functionality from that repo.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 8 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28#-MnbDAuu8I75w7CN4GRA:-MnbDAuvCLjjqkQxSkqv:b2vis6a) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ae79a62fe76dc6afd5417dfd03c6b2866da42fd9/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L36)):*
> ```Kotlin
>   dataProviderListSalt: ByteString
> ): ByteString {
>   return hashSha256(dataProviderList.concat(dataProviderListSalt))
> ```

are these equivalent? I know our spec says to concat but its equivalent, the previous is slightly more straightforward.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28#-MnbDFZn10LLmhZgiM_t:-MnbDFZn10LLmhZgiM_u:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ae79a62fe76dc6afd5417dfd03c6b2866da42fd9/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L69)):*
> ```Kotlin
>     .apply {
>       dataProviderListHash =
>         hashSha256(SOME_SERIALIZED_DATA_PROVIDER_LIST.concat(SOME_DATA_PROVIDER_LIST_SALT))
> ```

ditto
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28#-MnbDSTc4FJAKV5w9o9z:-MnbDSTc4FJAKV5w9oA-:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ae79a62fe76dc6afd5417dfd03c6b2866da42fd9/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L57)):*
> ```Kotlin
>     .apply {
>       dataProviderListHash =
>         hashSha256(SOME_SERIALIZED_DATA_PROVIDER_LIST.concat(SOME_DATA_PROVIDER_LIST_SALT))
> ```

ditto

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28#-MnbDAuu8I75w7CN4GRA:-MnbP3vfDicLdrywdrmo:b-29zyy9) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ae79a62fe76dc6afd5417dfd03c6b2866da42fd9/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are these equivalent? I know our spec says to concat but its equivalent, the previous is slightly more straightforward.
</blockquote></details>

The follow-up PR #29 drops this anyway, so this is very temporary, I just wanted to isolate the changes from updating common-jvm from the ones for implementing the new consent signaling protocol into two separate PRs.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28#-MnbDFZn10LLmhZgiM_t:-MnbPq_Y386mYOvTk8y9:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ae79a62fe76dc6afd5417dfd03c6b2866da42fd9/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L69)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Ditto
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28#-MnbDSTc4FJAKV5w9o9z:-MnbPt5k8Y4QPGJFhCEA:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ae79a62fe76dc6afd5417dfd03c6b2866da42fd9/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L57)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Ditto

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
