### PR TITLE
Specify signature algorithm where needed.

### PR DESCRIPTION
**Pull request by SanjayVas**
Updates common-jvm to 0.67.0 and cross-media-measurement-api to 0.45.0

### CODE REVIEW

**Comment by SanjayVas** [comment]
Depends on:

- https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/177
- https://github.com/world-federation-of-advertisers/common-jvm/pull/218

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46#-NfWNKTEA5CLDBnaYK-_:-NfWNKTEA5CLDBnaYK-a:btq5fx5) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/33b87b38e26a7d4ddb9d15ff1c62e4d00d790693/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L49)):*
> ```Kotlin
>  * The [measurementConsumerSigningKey] determines the algorithm type of the signature.
>  */
> fun signRequisitionSpec(
> ```

wdyt about deprecating the original function and then adding a new function without a default?

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46#-NfWNKTEA5CLDBnaYK-_:-NfXVkhG1yYlElaoEDCa:b3j279l) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/33b87b38e26a7d4ddb9d15ff1c62e4d00d790693/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L49)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wdyt about deprecating the original function and then adding a new function without a default?
</blockquote></details>

I actually had that initially and then changed it when I realized I was duplicating the same code at every call site.

It's entirely fine to have our code pick the signature algorithm for you for signing when it can return which algorithm it picked, which is true for the case of anything that returns a `SignedData`. Where you need to specify it explicitly is for verification or for cases where there's no way to learn what algorithm was chosen on your behalf.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46#-NfWNKTEA5CLDBnaYK-_:-NfXcrs71Tk9O603coD3:bj5qpup) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/33b87b38e26a7d4ddb9d15ff1c62e4d00d790693/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I actually had that initially and then changed it when I realized I was duplicating the same code at every call site.

It's entirely fine to have our code pick the signature algorithm for you for signing when it can return which algorithm it picked, which is true for the case of anything that returns a `SignedData`. Where you need to specify it explicitly is for verification or for cases where there's no way to learn what algorithm was chosen on your behalf.
</blockquote></details>

I'd prefer to encourage adopters to pass in the value explicitly.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46#-NfWNKTEA5CLDBnaYK-_:-NfXpBHRAXqohfy_h_VV:bul42q1) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/33b87b38e26a7d4ddb9d15ff1c62e4d00d790693/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L49)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer to encourage adopters to pass in the value explicitly.
</blockquote></details>

That's a **big** churn across all of our call sites when none of them will use anything other than the default. This is about giving the callers the *option* to specify a different algorithm if they desire.

It's also a bit of a code smell to pass both an object and a property of said object into the same function.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46#-NfWNKTEA5CLDBnaYK-_:-NfkGhut34wTM0CZrJGS:b955bui) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/33b87b38e26a7d4ddb9d15ff1c62e4d00d790693/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's a **big** churn across all of our call sites when none of them will use anything other than the default. This is about giving the callers the *option* to specify a different algorithm if they desire.

It's also a bit of a code smell to pass both an object and a property of said object into the same function.
</blockquote></details>

I prefer, in general, that security params be explicitly stated. Unblocking however for now.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
