### PR TITLE
Check legacy serialized_measurement_public_key fields.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/50)

**Comment by SanjayVas** [comment]
See https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1596

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/50)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`.bazelversion` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/50#-Nwt4NvJ0cL953PciX2j:-Nwt4NvJ0cL953PciX2k:b-dw3jbg) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/5f9505f1f59107b62490d5d9ba84fca5d6902a1b/.bazelversion#L1)):*
> ```
> 7.1.1
> ```

Just for my understanding: is this upgrade a requirement for the code itself or just to stay up to date?

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @Marco-Premier from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/50)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
