### PR TITLE
Add MeasurementSpec and RequisitionSpec functions

### PR DESCRIPTION
**Pull request by corbantek**
- Add verifyMeasurementSpec to Kingdom Client
- Add verifyMeasurementSpec and verifyRequisitionSpec to DataProviderClient

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-Mh-SOZb9pmH72HA1E00:-Mh-SOZb9pmH72HA1E01:bzdmi50) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/5f2f3a9de212a915dc595ccc32715efcbe261b28/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L81)):*
> ```Kotlin
>     certificate = dataProviderCertificate
>   )
> }
> ```

everything looks good.

 The only missing one I can think of is `verifyElGamalPublicKey()` for https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L81

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

**Review by corbantek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-Mh-SOZb9pmH72HA1E00:-Mh1epf86C68Kd0hYwkx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/5f2f3a9de212a915dc595ccc32715efcbe261b28/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L81)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

everything looks good.

 The only missing one I can think of is `verifyElGamalPublicKey()` for https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L81
</blockquote></details>

Done.

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFplfg96vZIq9XQSYT:-MhFplfg96vZIq9XQSYU:b-fpkcwx) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L81)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> val MC_CERTIFICATE: X509Certificate = readCertificate(MC_1_CERT_PEM_FILE)
> const val MC_PRIVATE_KEY_HANDLE_KEY = "mc1"
> val EDP_CERTIFICATE: X509Certificate = readCertificate(EDP_1_CERT_PEM_FILE)
> const val EDP_PRIVATE_KEY_HANDLE_KEY = "edp1"
> val EDP_PUBLIC_KEY = EncryptionPublicKey.getDefaultInstance()
> val DUCHY_CERTIFICATE: X509Certificate = readCertificate(DUCHY_1_NON_AGG_CERT_PEM_FILE)
> const val DUCHY_PRIVATE_KEY_HANDLE_KEY = "duchy1"
> ```
</details>


can these be private?
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFqERk5FuTe06W09Dj:-MhFqERk5FuTe06W09Dk:b-tezjcq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L90)):*
> ```
> class DataProviderClientTest {
> ```
@RunWith(JUnit4::class)
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFqzQh9jSuyynDHIAO:-MhFqzQh9jSuyynDHIAP:b-hu6m79) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L94)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   companion object {
>     @BeforeClass
>     @JvmStatic
>     fun initializePrivateKeyKeystore() {
> ```
</details>


For consistency, maybe use @Before.
```
@Before
  fun setup() = runBlocking {
      keyStore.storePrivateKeyDer(
          MC_PRIVATE_KEY_HANDLE_KEY,
          ByteString.copyFrom(
            readPrivateKey(MC_1_KEY_FILE, MC_CERTIFICATE.publicKey.algorithm).encoded
          )
        )
        keyStore.storePrivateKeyDer(
          EDP_PRIVATE_KEY_HANDLE_KEY,
          ByteString.copyFrom(
            readPrivateKey(EDP_1_KEY_FILE, EDP_CERTIFICATE.publicKey.algorithm).encoded
          )
        )
        keyStore.storePrivateKeyDer(
          DUCHY_PRIVATE_KEY_HANDLE_KEY,
          ByteString.copyFrom(
            readPrivateKey(DUCHY_1_NON_AGG_KEY_FILE, DUCHY_CERTIFICATE.publicKey.algorithm).encoded
          )
        )

  }
```
e.g., https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt#L84
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFrcNA3sJfTckSzEL5:-MhFrcNA3sJfTckSzEL6:b-b2mdd2) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L74)):*
> ```
> class DuchyClientTest {
> ```

@RunWith(JUnit4::class)
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/kingdom/KingdomClientTest.kt, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFrfaXE46ziz3Bffg0:-MhFrfaXE46ziz3Bffg1:bp5rf0k) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/kingdom/KingdomClientTest.kt#L51)):*
> ```
> class KingdomClientTest {
> ```
 same here and the MeasurementConsumerTest

**Review by corbantek — COMMENTED** [review]
> Dismissed @wangyaopw from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFplfg96vZIq9XQSYT:-MhHEbWBAh0mUOT2EVF1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L81)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> val MC_CERTIFICATE: X509Certificate = readCertificate(MC_1_CERT_PEM_FILE)
> const val MC_PRIVATE_KEY_HANDLE_KEY = "mc1"
> val EDP_CERTIFICATE: X509Certificate = readCertificate(EDP_1_CERT_PEM_FILE)
> const val EDP_PRIVATE_KEY_HANDLE_KEY = "edp1"
> val EDP_PUBLIC_KEY = EncryptionPublicKey.getDefaultInstance()
> val DUCHY_CERTIFICATE: X509Certificate = readCertificate(DUCHY_1_NON_AGG_CERT_PEM_FILE)
> const val DUCHY_PRIVATE_KEY_HANDLE_KEY = "duchy1"
> ```

can these be private?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFqERk5FuTe06W09Dj:-MhHFTvV4qt0OL1nFLXl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L90)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> class DataProviderClientTest {
> ```
@RunWith(JUnit4::class)
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFqzQh9jSuyynDHIAO:-MhHFUda1zZ2smzXsq4e:b-w5k5nq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L94)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>   companion object {
>     @BeforeClass
>     @JvmStatic
>     fun initializePrivateKeyKeystore() {
> ```

For consistency, maybe use @Before.
```
@Before
  fun setup() = runBlocking {
      keyStore.storePrivateKeyDer(
          MC_PRIVATE_KEY_HANDLE_KEY,
          ByteString.copyFrom(
            readPrivateKey(MC_1_KEY_FILE, MC_CERTIFICATE.publicKey.algorithm).encoded
          )
        )
        keyStore.storePrivateKeyDer(
          EDP_PRIVATE_KEY_HANDLE_KEY,
          ByteString.copyFrom(
            readPrivateKey(EDP_1_KEY_FILE, EDP_CERTIFICATE.publicKey.algorithm).encoded
          )
        )
        keyStore.storePrivateKeyDer(
          DUCHY_PRIVATE_KEY_HANDLE_KEY,
          ByteString.copyFrom(
            readPrivateKey(DUCHY_1_NON_AGG_KEY_FILE, DUCHY_CERTIFICATE.publicKey.algorithm).encoded
          )
        )

  }
```
e.g., https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt#L84
</blockquote></details>

The reason I'm using `@BeforeClass` is this only needs to run once before any of the tests run.  If you use `@Before` then it will re-store the keys over and over before each individual test runs. 

Technically both have the same outcome, but seems like an unneeded execution of code to run before every test when once is fine.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFrcNA3sJfTckSzEL5:-MhHHz0aDJkUA3Su6ywA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L74)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> class DuchyClientTest {
> ```

@RunWith(JUnit4::class)
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/kingdom/KingdomClientTest.kt, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFrfaXE46ziz3Bffg0:-MhHI4yg8727chP-43OH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/kingdom/KingdomClientTest.kt#L51)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> class KingdomClientTest {
> ```
 same here and the MeasurementConsumerTest
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFqzQh9jSuyynDHIAO:-MhJnoWS-Oq3Jxdr_I4f:b4so0ft) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L94)):*
> ```
> BeforeClass
> ```
that makes sense. 

nit: we usually put companion object at the bottom of the class.

**Review by wangyaopw — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-:-MhJoBFS-9JtZOxg_eNK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

**Review by corbantek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFqzQh9jSuyynDHIAO:-MhJpRgW34cF-lAyBZeK:bkgbgzz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L94)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> BeforeClass
> ```
that makes sense. 

nit: we usually put companion object at the bottom of the class.
</blockquote></details>

Yeah @sanjayvas mentioned that last time, and normally I agree, but I find it hard to read when variables are initialized below their usage.  All this companion object is a weird Kotlin workaround for @BeforeClass static method from Java for JUnit.

**Review by corbantek — COMMENTED** [review]
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/15#-MhFqzQh9jSuyynDHIAO:-MhJtw3C8sJ4asxa2Ytn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e3646c86d71e3343ff449458feeab858a0e06b6a/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L94)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Yeah @sanjayvas mentioned that last time, and normally I agree, but I find it hard to read when variables are initialized below their usage.  All this companion object is a weird Kotlin workaround for @BeforeClass static method from Java for JUnit.
</blockquote></details>

Done.

**Pull request merged**
