### PR TITLE
Update cross-media-measurement-api to 0.14.0.

### PR DESCRIPTION
**Pull request by SanjayVas**
This handles the API changes to use nonces for verification of EDP participation.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This is intended to be merged into `main` after parent PR #28.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MnazmeFAJyf5OFF23I4:-MnazmeG5LJ1V1N7gjx0:b-99cu2k) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ce2f7438cf343bc4f6fc3751ddff34339f06b37e/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L58)):*
> ```Kotlin
>  * 3. Verify that the list in [measurementSpec] contains the nonce hash.
>  */
> fun verifyDataProviderParticipation(
> ```

I assume this is called by the duchy when a requisition is being fulfilled.

What method the duchy calls later to verify all EDPs' participation? Duchy only needs to check if the kingdom gets the lists of nonces that match the list of nonceHashes.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MnbGBz1340bj-ya-NDv:-MnbGBz1340bj-ya-NDw:b-59jjo0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ce2f7438cf343bc4f6fc3751ddff34339f06b37e/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L125)):*
> ```Kotlin
>   ) &&
>     requisitionSpec.measurementPublicKey.equals(measurementSpec.measurementPublicKey) &&
>     measurementSpec.nonceHashesList.contains(hashSha256(requisitionSpec.nonce))
> ```

isn't the EDP initially only given a single hash, not a list?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MnazmeFAJyf5OFF23I4:-MnbGQjCAHg2EdDRqp-H:b-nri7ur) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ce2f7438cf343bc4f6fc3751ddff34339f06b37e/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L58)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I assume this is called by the duchy when a requisition is being fulfilled.

What method the duchy calls later to verify all EDPs' participation? Duchy only needs to check if the kingdom gets the lists of nonces that match the list of nonceHashes.
</blockquote></details>

I have the same question as Yao. Can this be clarified in the comments too?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MnbGBz1340bj-ya-NDv:-Mnbb1xzAVlBq1_Zlk7a:b-rxewsr) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ce2f7438cf343bc4f6fc3751ddff34339f06b37e/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L125)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

isn't the EDP initially only given a single hash, not a list?
</blockquote></details>

It has its own single nonce from the RequisitionSpec and the list of nonce hashes from the MeasurementSpec.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MnazmeFAJyf5OFF23I4:-MnbbTNh9GZ7--1D0Hsq:bw7bk7m) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ce2f7438cf343bc4f6fc3751ddff34339f06b37e/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I have the same question as Yao. Can this be clarified in the comments too?
</blockquote></details>

Ah, you're right that method is missing. Let me add it.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MnazmeFAJyf5OFF23I4:-Mnbu86m473OGN3RSSg5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ce2f7438cf343bc4f6fc3751ddff34339f06b37e/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, you're right that method is missing. Let me add it.
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[build/consent_signaling_client_repositories.bzl, line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MoKh1M22SRxp48P3i0C:-MoKh1M22SRxp48P3i0D:b9zwc7t) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/6b75288f44739d2bc13d92ae5e7aca4d7e0deb67/build/consent_signaling_client_repositories.bzl#L38)):*
> ```Starlark
>         url = "https://github.com/world-federation-of-advertisers/cross-media-measurement-api/archive/refs/tags/v0.13.0.tar.gz",
>     )
>     http_archive(
> ```

`v0.14.0` has been released, should we use that?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @wangyaopw)

___
*[build/consent_signaling_client_repositories.bzl, line 38 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MoKh1M22SRxp48P3i0C:-MoKiFcKAZtpmvSjRV2K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/6b75288f44739d2bc13d92ae5e7aca4d7e0deb67/build/consent_signaling_client_repositories.bzl#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`v0.14.0` has been released, should we use that?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 97 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MoKrShC-LwEYhVTPhFN:-MoKrShC-LwEYhVTPhFO:b-1zshbf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/46292df24c15e5339135c057300e47f1b390f3b5/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L97)):*
> ```Kotlin
>     val requisition = Requisition(requisitionFingerprint, NONCE_HASH.bytes)
> 
>     assertFalse(
> ```

Haven't we mostly been using `assertThat(x).isFalse()`? Or do we use `assertTrue`/`assertFalse`?

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MnbGBz1340bj-ya-NDv:-MoKzdi8AEjzgFBB2Euh:b-od3s7u) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ce2f7438cf343bc4f6fc3751ddff34339f06b37e/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L125)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It has its own single nonce from the RequisitionSpec and the list of nonce hashes from the MeasurementSpec.
</blockquote></details>

perfect. thx for the clarification.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @efoxepstein and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 97 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29#-MoKrShC-LwEYhVTPhFN:-MoKuBu2594V3EZphc0R:b-qldi1j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/46292df24c15e5339135c057300e47f1b390f3b5/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L97)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Haven't we mostly been using `assertThat(x).isFalse()`? Or do we use `assertTrue`/`assertFalse`?
</blockquote></details>

Hmm, I was trying to find the advice I had seen that suggested not bothering with Truth for true/false, but I can't. Instead, I see that Google-internal analyzers will suggest switching to Truth.

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
