### PR TITLE
Use PrivateKeyHandle from common-jvm for hybrid encryption operations.

### PR DESCRIPTION
**Pull request by SanjayVas**
This removes the now-unused crypto package.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34)

https://rally1.rallydev.com/#/?detail=/task/619013800849&fdp=true

### CODE REVIEW

**Comment by SanjayVas** [comment]
Waiting on a new release with https://github.com/world-federation-of-advertisers/common-jvm/pull/70.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34)* status: 0 of 39 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34#-MqaD1sh0NOz0JrDUgA5:-MqaD1sh0NOz0JrDUgA6:brxj2gh) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f7cd20f2b9056f6646be07e886741f4f2705b409/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L54)):*
> ```
>  * @param encryptedSignedDataRequisitionSpec an encrypted [SignedData] containing a
>  * [RequisitionSpec]
> ```
add @param for both or none of the parameters.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34#-MqaCvOYECORWOpqLFU3:-MqaCvOYECORWOpqLFU4:b-4amhds) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f7cd20f2b9056f6646be07e886741f4f2705b409/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L59)):*
> ```
> org.wfanet.measurement.common.crypto.PrivateKeyHandle
> ```

import?
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 85 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34#-MqaE5wM7NwrzwBeSWMF:-MqaE5wM7NwrzwBeSWMG:bccojsg) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/13274411b6192cf0d06431348b4cedc5a3d843c2/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L85)):*
> ```
> fun `data provider calculates requisition participation signature`() = runBlocking {
> ```

Instead of deleting this one,  update it to test the `computeRequisitionFingerprint()` method?

Maybe it is fine to delete it since it is kind of covered in the duchyClientTest. up to you.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34)* status: 0 of 39 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34#-MqaD1sh0NOz0JrDUgA5:-MqaaiOP5IjXE8XDAZyF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f7cd20f2b9056f6646be07e886741f4f2705b409/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L54)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  * @param encryptedSignedDataRequisitionSpec an encrypted [SignedData] containing a
>  * [RequisitionSpec]
> ```
add @param for both or none of the parameters.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34#-MqaCvOYECORWOpqLFU3:-Mqaai0s3TTwWmrRp3lW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f7cd20f2b9056f6646be07e886741f4f2705b409/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L59)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> org.wfanet.measurement.common.crypto.PrivateKeyHandle
> ```

import?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 85 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34#-MqaE5wM7NwrzwBeSWMF:-MqaLlxa9Tkids--GZvX:b-nc3rh0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/13274411b6192cf0d06431348b4cedc5a3d843c2/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L85)):*
> Maybe it is fine to delete it since it is kind of covered in the duchyClientTest. up to you.

Yeah, it gets covered by `DuchyClientTest`. There's not really a meaningful way to test this function on its own.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 36 of 39 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
