### PR TITLE
Update cross-media-measurement-api dep for type URLs.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by SanjayVas** [comment]
Depends on https://github.com/world-federation-of-advertisers/common-jvm/pull/219 and https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/185

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/common/KeyHandles.kt` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTR1_t1Z-kZ_xPoXmg:-NhTR1_t1Z-kZ_xPoXmh:b-r3auxr) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/common/KeyHandles.kt#L22)):*
> ```Kotlin
> import com.google.protobuf.ByteString
> import com.google.protobuf.Message
> import com.google.protobuf.any
> ```

`as protoAny` to be consistent
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/common/KeyHandles.kt` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTUWU96Jd4fxlmEtvb:-NhTUWUA6nclClGHT7ou:b-rjivi5) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/common/KeyHandles.kt#L75)):*
> ```Kotlin
>   return any {
>       value = plaintext
>       typeUrl = encryptedMessage.typeUrl
> ```

what kind of checks can we provide to ensure that T and typeUrl are compatible?
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/common/Signing.kt` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWGJO7nSD7GgdXpM3:-NhTWGJO7nSD7GgdXpM4:buxojvd) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/common/Signing.kt#L34)):*
> ```Kotlin
>   algorithm: SignatureAlgorithm = signingKey.defaultAlgorithm
> ): SignedMessage {
>   val packed = ProtoAny.pack(this)
> ```

you can just use your helper from common-jvm
```
val packed = this.pack()
```

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 161 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWsJcAZ7XJL6cyl-v:-NhTWsJcAZ7XJL6cyl-w:bjgt2ac) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L161)):*
> ```Kotlin
>   measurementConsumerPublicKey: EncryptionPublicKey
> ): EncryptedMessage =
>   measurementConsumerPublicKey.toPublicKeyHandle().encryptMessage(ProtoAny.pack(metadata))
> ```

metadata.pack()
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWkLgECAkBK8EAb7j:-NhTWkLgECAkBK8EAb7k:bsxrbiz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L165)):*
> ```Kotlin
> /** Encrypts [signedResult] using [measurementConsumerPublicKey]. */
> fun encryptResult(signedResult: SignedMessage, measurementConsumerPublicKey: EncryptionPublicKey) =
>   measurementConsumerPublicKey.toPublicKeyHandle().encryptMessage(ProtoAny.pack(signedResult))
> ```

```
measurementConsumerPublicKey.toPublicKeyHandle().encryptMessage(signedResult.pack())
```

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt` line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWuQa5EgpmzNBnqV5:-NhTWuQa5EgpmzNBnqV6:b-iz2x3q) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L101)):*
> ```Kotlin
>   measurementPublicKey: EncryptionPublicKey,
> ): EncryptedMessage {
>   return measurementPublicKey.toPublicKeyHandle().encryptMessage(ProtoAny.pack(signedResult))
> ```

signedResult.pack()
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt` line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWxR66xjlMffEjkgw:-NhTWxR66xjlMffEjkgx:b-atkoi6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L72)):*
> ```Kotlin
>   return measurementPublicKey
>     .toPublicKeyHandle()
>     .encryptMessage(ProtoAny.pack(signedRequisitionSpec))
> ```

signedRequisitionSpec.pack()

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47)* status: 5 of 15 files reviewed, 7 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/common/KeyHandles.kt` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTR1_t1Z-kZ_xPoXmg:-NhTwVNd4uzKsjBXiIT1:b-fc68l4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/common/KeyHandles.kt#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`as protoAny` to be consistent
</blockquote></details>

I had considered this originally and chose not to alias:

We only use the alias for `com.google.protobuf.Any` to avoid conflicting with `kotlin.Any`. There's no such conflict for the `com.google.protobuf.any` DSL factory, as it wouldn't even make sense to have a factory for `kotlin.Any` (it's just a base type marker like `java.lang.Object`). I'm not sure it would make sense to do the same alias for that factory for files that don't end up importing/aliasing `com.google.protobuf.Any`, so the presence of the latter alias would end up depending on the presence of the former.

Contrast this with the the case where we alias both the type and the factory together: disambiguating between public vs. internal APIs. There we often have a high probability of importing DSL factories for both. We only do this in the public API service impls, as that's the place where both APIs need to coexist.

Therefore, I think we'd provide better consistency by *not* aliasing the DSL factory.
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/common/KeyHandles.kt` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTUWU96Jd4fxlmEtvb:-NhTr4Ma5_YIivrF0rog:b-u3sxof) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/common/KeyHandles.kt#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what kind of checks can we provide to ensure that T and typeUrl are compatible?
</blockquote></details>

`unpack` will throw an `InvalidProtocolBufferException` with the message "Type of the Any message does not match the given class." in that case.

I added some documentation to surface this.
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/common/Signing.kt` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWGJO7nSD7GgdXpM3:-NhTwqFKCDySOmrn_GbM:bl4fgw) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/common/Signing.kt#L34)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you can just use your helper from common-jvm
```
val packed = this.pack()
```

</blockquote></details>

Done. I had added that helper after writing this PR.
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 161 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWsJcAZ7XJL6cyl-v:-NhTwu7I9Wa-7mXB7_Qr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L161)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

metadata.pack()
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWkLgECAkBK8EAb7j:-NhTwui68Ve-IcqKAErf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L165)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

```
measurementConsumerPublicKey.toPublicKeyHandle().encryptMessage(signedResult.pack())
```

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt` line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWuQa5EgpmzNBnqV5:-NhTww-9AGZGEabVMuSb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L101)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

signedResult.pack()
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt` line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47#-NhTWxR66xjlMffEjkgw:-NhTwwUT5ncaz7xoHmws:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/87a35ea89df5c99f0a9924539cd6f54eabdd37e5/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L72)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

signedRequisitionSpec.pack()
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
