### PR TITLE
Use SigningKeyHandle for all signing private keys.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/33)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This is intended to be merged into main after parent PR #32.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 7 of 13 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/33)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/common/BUILD.bazel, line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/33#-MqVJSiq3ADZHaTISrJG:-MqVJSiq3ADZHaTISrJH:bn3ju0z) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/792ffa212cab74d92f447048ea22ff29bb0bbe4c/src/main/kotlin/org/wfanet/measurement/consent/client/common/BUILD.bazel#L3)):*
> ```
> fault_visibility = ["//visibility:public"])
> ```

Should this be package private or not? if it is public, the user is highly likely to just call signMessage() on everything directly.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/33)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/common/BUILD.bazel, line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/33#-MqVJSiq3ADZHaTISrJG:-MqVZdRLB1NDFzabG8FL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/792ffa212cab74d92f447048ea22ff29bb0bbe4c/src/main/kotlin/org/wfanet/measurement/consent/client/common/BUILD.bazel#L3)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> fault_visibility = ["//visibility:public"])
> ```

Should this be package private or not? if it is public, the user is highly likely to just call signMessage() on everything directly.
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/33)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 13 files at r1, 8 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/33)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.kt, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/33#-MqWAy-LE27JdVRX-7eI:-MqWAy-LE27JdVRX-7eJ:b-j5u5us) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/27436058242a4727d823e4bf4072d77af3481587/src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.kt#L28)):*
> ```Kotlin
> 
> /** Generic for signing [Message]s. Used by client functions to show consent. */
> suspend fun <T : Message> signMessage(
> ```

is this internal? do we want to add a deprecation notice?

**Pull request merged**
