### PR TITLE
Add signature and encryption functions to clients

### PR DESCRIPTION
**Pull request by renjiezh**
`signMessage()` is used directly by cross-media-measurement.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)

### CODE REVIEW

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> signMessage() is used directly by cross-media-measurement.

If this is true, then it would imply that cross-media-measurement fails to build. Was this something that was changed in a version of consent-signaling-client that cross-media-measurement isn't yet using? Normally we'd point out the offending PR in this case.

That said, I imagine the correct fix would actually be to fix cross-media-measurement to not call `signMessage` from consent-signaling-client directly, as I believe this goes against the intent of the library design. IIRC, the idea was that all calls related to consent signaling were supposed to go to a `client`method with the specific CMMS API message types, which in turn could delegate to the `common` method.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39#-:-N8jwmeZ39k_fWdEO6we:b43rthk)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
+1

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39#-:-N8y2YDJ7DZ6dQ3k0MZ4:b32v57)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
Added two sign functions.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39#-:-N8yTRmPEChxCe0HhFz7:bsympbx)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39#-N92KK9WBr7svXbojlu4:-N92KK9WBr7svXbojlu5:b9uvub1) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3c26a7c3a07fbd49b31e1a427949a6daa67b810a/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L117)):*
> ```Kotlin
>  * The [dataProviderSigningKey] determines the algorithm type of the signature.
>  */
> fun signMetadata(metadata: Metadata, dataProviderSigningKey: SigningKeyHandle): SignedData {
> ```

where is this used? I thought we were just encrypting the Metadata -- https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/17a03006b0e2bccf897f48bc516883d165aa910b/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L86

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39#-N92KK9WBr7svXbojlu4:-N92YqCB-Qe_auzQUytY:b-liwl0h) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3c26a7c3a07fbd49b31e1a427949a6daa67b810a/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L117)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

where is this used? I thought we were just encrypting the Metadata -- https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/17a03006b0e2bccf897f48bc516883d165aa910b/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L86
</blockquote></details>

It is used in a test case.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L127-L133

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39#-N92KK9WBr7svXbojlu4:-N92hC0h4yt6E40gEdIo:b-bvej79) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3c26a7c3a07fbd49b31e1a427949a6daa67b810a/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L117)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

It is used in a test case.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L127-L133
</blockquote></details>

@sanjayvas as i understand it, the spec on the public api is that the meta data is only encrypted, not also signed -- https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/17a03006b0e2bccf897f48bc516883d165aa910b/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L86

If we want to also require it to be signed, can we update the public api?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39#-N92KK9WBr7svXbojlu4:-N92kqvYAJSR23nccqN_:b-i2wl5w) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3c26a7c3a07fbd49b31e1a427949a6daa67b810a/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L117)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@sanjayvas as i understand it, the spec on the public api is that the meta data is only encrypted, not also signed -- https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/17a03006b0e2bccf897f48bc516883d165aa910b/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L86

If we want to also require it to be signed, can we update the public api?
</blockquote></details>

It looks like it's the test itself that's incorrect here.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39#-N92KK9WBr7svXbojlu4:-N92mSED1Go_DEoTKBwq:brbjkdg) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3c26a7c3a07fbd49b31e1a427949a6daa67b810a/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L117)):*
> e want to also require it to be signed,
I see. I will remove `signMetadata` and fix the test while bumping common-jvm.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt` line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39#-N92KK9WBr7svXbojlu4:-N92miet-C8yHoJN8sz7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3c26a7c3a07fbd49b31e1a427949a6daa67b810a/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L117)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

> e want to also require it to be signed,
I see. I will remove `signMetadata` and fix the test while bumping common-jvm.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
