### PR TITLE
Add method for verifying double signature of exchange step

### PR DESCRIPTION
**Pull request by duliomatos1**
verifyExchangeStepSignatures() will be used in panel-exchange-client
to implement the ExchangeStepValidator

https://rally1.rallydev.com/#/?detail=/task/608172238481&fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 11 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 11 of 17 files reviewed, 2 unresolved discussions (waiting on @duliomatos1)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 150 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBHheb85ch5-V4jIIw:-MjBHhecBjeXDoEJm6zj:b-u7p4n1) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L150)):*
> ```Kotlin
>  * [modelProviderCertificate] and [dataProviderCertificate]
>  */
> fun verifyExchangeStepSignatures(
> ```

Can you combine the shared logic of the two duplicate functions and put in a helper function, maybe here: src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.k
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBFKx1B0Y3nR4A70X_:-MjBFKx1B0Y3nR4A70Xa:buc3kym) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt#L32)):*
> ```Kotlin
>   )
> 
> fun loadTestFile(filename: String): File =
> ```

private

**Review by jonmolle — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 17 files reviewed, 4 unresolved discussions (waiting on @duliomatos1)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBGDtq-kFhq_UT6Awr:-MjBGDtq-kFhq_UT6Aws:b-6fhtk4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L147)):*
> ```Kotlin
> }
> 
> /** Verifies that the [signedExchangeWorkflow] was signed by both the entities represented by
> ```

Why have this duplicated in both clients? Do we expect this step to diverge for a EDP and MP?
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/AbstractExchangeStepSignaturesTest.kt, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBGnZI-Criq1QgJycJ:-MjBGnZI-Criq1QgJycK:baubdpk) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/testing/AbstractExchangeStepSignaturesTest.kt#L81)):*
> ```Kotlin
>   companion object {
>     private val random = Random.Default
>     private val randomSignature: ByteString = random.nextBytes(70).toByteString()
> ```

Optional: Does this have to be random (vs a private val at the top of file)? I don't really see how this could be a problem, so whatever you decide is ok, I'm just always a bit wary of adding variability into a unit test (in case it makes something flaky).

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 17 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBGDtq-kFhq_UT6Awr:-MjBJDBD6NemLSi_0bzO:b-uvq6oj) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L147)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Why have this duplicated in both clients? Do we expect this step to diverge for a EDP and MP?
</blockquote></details>

I don't expect this to diverge. Maybe @stevenwarejones's rationale to suggest this was to have all related functions for MC and DP clients in the respective package? As an example I can see that we have copies of `signEncryptionPublicKey()` in both as well, with a different param name for the certificate
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 150 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBHheb85ch5-V4jIIw:-MjBNAw4E7k38rVxPALo:b-5nq13u) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L150)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Can you combine the shared logic of the two duplicate functions and put in a helper function, maybe here: src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.k
</blockquote></details>

Would simplify the code for sure. @stevenwarejones, in this case, would you prefer to keep a function pointing to this combined one inside MC Client and DP Client?
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/AbstractExchangeStepSignaturesTest.kt, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBGnZI-Criq1QgJycJ:-MjBJTlq0psT3GdIbnnp:bk3rsul) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/testing/AbstractExchangeStepSignaturesTest.kt#L81)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Optional: Does this have to be random (vs a private val at the top of file)? I don't really see how this could be a problem, so whatever you decide is ok, I'm just always a bit wary of adding variability into a unit test (in case it makes something flaky).
</blockquote></details>

Fair point, I can generate a random bytstring as a private val, and it's only a few bytes.

We use the same method of using `Random` to generate bytes inside `AbstractStorageClientTest`, but there it's a few MB of data for a `testBlobContent`

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 17 files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBGDtq-kFhq_UT6Awr:-MjCF7Fj02C3PcMvejrU:bn6r7y3) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L147)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I don't expect this to diverge. Maybe @stevenwarejones's rationale to suggest this was to have all related functions for MC and DP clients in the respective package? As an example I can see that we have copies of `signEncryptionPublicKey()` in both as well, with a different param name for the certificate
</blockquote></details>

the way this repo is currently set up, functions are somewhat duplicated per client. The expectation is that the client shouldn't need to know which function to call.... it just uses the functions in its client file.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 150 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBHheb85ch5-V4jIIw:-MjCFLIR9J4iSwK5DWle:b-dxatdn) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L150)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Would simplify the code for sure. @stevenwarejones, in this case, would you prefer to keep a function pointing to this combined one inside MC Client and DP Client?
</blockquote></details>

yes - one function in each file (per the convention of the repo currently), but each one a one-liner basically that uses the helper function.
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/AbstractExchangeStepSignaturesTest.kt, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBGnZI-Criq1QgJycJ:-MjCFVKf4RNTt47fGcBN:b-li77x1) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/testing/AbstractExchangeStepSignaturesTest.kt#L81)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Fair point, I can generate a random bytstring as a private val, and it's only a few bytes.

We use the same method of using `Random` to generate bytes inside `AbstractStorageClientTest`, but there it's a few MB of data for a `testBlobContent`
</blockquote></details>

just call it "some-random-bytestring".toByteString()

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 17 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 147 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBGDtq-kFhq_UT6Awr:-MjFjnVECxmFlRkpgi2f:b5oljmy) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L147)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the way this repo is currently set up, functions are somewhat duplicated per client. The expectation is that the client shouldn't need to know which function to call.... it just uses the functions in its client file.
</blockquote></details>

I think the suggestion below of having an alias function call a helper would solve the concern I have (of having to keep 2 places in sync with identical logic).
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 150 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBHheb85ch5-V4jIIw:-MjFjg403FebjpxDtvS9:b-825l3c) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L150)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yes - one function in each file (per the convention of the repo currently), but each one a one-liner basically that uses the helper function.
</blockquote></details>

This seems like a good idea to me, as well, my main concern is these two getting out of sync unintentionally.

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 11 of 18 files reviewed, 3 unresolved discussions (waiting on @jonmolle and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 150 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBHheb85ch5-V4jIIw:-MjGHPVk1llHy0IVA98j:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L150)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

This seems like a good idea to me, as well, my main concern is these two getting out of sync unintentionally.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/AbstractExchangeStepSignaturesTest.kt, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBGnZI-Criq1QgJycJ:-MjGHS5PCeEiN1iGxZ3B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/testing/AbstractExchangeStepSignaturesTest.kt#L81)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

just call it "some-random-bytestring".toByteString()
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjBFKx1B0Y3nR4A70X_:-MjGHl8_Bw0scKj12Qqj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1b1de088b1bfb2ecb29392bf64523427c231c24/src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

private
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 18 files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 162 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNDtj4PGIwDAIZ9wa:-MjGNDtj4PGIwDAIZ9wb:b-qn66zq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L162)):*
> ```Kotlin
>   modelProviderCertificate: X509Certificate,
>   dataProviderCertificate: X509Certificate,
> ): Boolean = org.wfanet.measurement.consent.crypto.verifyExchangeStepSignatures(
> ```

nit: import this at the top
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 154 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNBUc2UedMyoRg8Ch:-MjGNBUd19706nw65mze:b-porqd7) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L154)):*
> ```Kotlin
>   modelProviderCertificate: X509Certificate,
>   dataProviderCertificate: X509Certificate,
> ): Boolean = org.wfanet.measurement.consent.crypto.verifyExchangeStepSignatures(
> ```

import this at the top
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.kt, line 58 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNT6220sGfJPOeAe8:-MjGNT638t7oC7M6qHaS:b-l4pepz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.kt#L58)):*
> ```Kotlin
>  * [modelProviderCertificate] and [dataProviderCertificate]
>  */
> fun verifyExchangeStepSignatures(
> ```

this util probably needs a test, but it feels a little duplicative to me.

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 18 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 162 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNDtj4PGIwDAIZ9wa:-MjGQQ0826arMZ_yTyZH:b-mkt6qe) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L162)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: import this at the top
</blockquote></details>

it has the same name as the current function. But I can import as `verifySignatures` or something
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 154 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNBUc2UedMyoRg8Ch:-MjGR7P62ED19YBSj5kz:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L154)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

import this at the top
</blockquote></details>

ditto

**Review by jonmolle — APPROVED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 18 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 18 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 162 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNDtj4PGIwDAIZ9wa:-MjV6FaF18yBBVOed7mD:b-thtyxg) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L162)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

it has the same name as the current function. But I can import as `verifySignatures` or something
</blockquote></details>

LGTM pending this change.

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 18 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 162 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNDtj4PGIwDAIZ9wa:-MjVA2ex9mHhv2XPSZ4M:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L162)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

LGTM pending this change.
</blockquote></details>

Done

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: 12 of 18 files reviewed, 3 unresolved discussions (waiting on @jonmolle and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.kt, line 58 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNT6220sGfJPOeAe8:-MjVA959-IoXCXh94Cmz:b-9oompz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this util probably needs a test, but it feels a little duplicative to me.
</blockquote></details>

agree, thought better to test the functions that will utilize it

**Review by duliomatos1 — COMMENTED** [review]
> Reviewed 11 of 17 files at r1, 1 of 1 files at r3, 3 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: all files reviewed, 3 unresolved discussions (waiting on @jonmolle and @stevenwarejones)

**Review by duliomatos1 — COMMENTED** [review]
> Dismissed @jonmolle and @stevenwarejones from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 154 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNBUc2UedMyoRg8Ch:-MjVNIICB05LC5iDbPSp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L154)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.kt, line 58 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19#-MjGNT6220sGfJPOeAe8:-MjVNSO40Pl13Trda2qJ:b2nhktp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b9c41ac817ac204fd5d5b19d2ccf6e47b1f1ce0e/src/main/kotlin/org/wfanet/measurement/consent/crypto/Utils.kt#L58)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

agree, thought better to test the functions that will utilize it
</blockquote></details>

OK.

**Review by duliomatos1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
