### PR TITLE
Add encryption and signature functions for HMSS RandomSeed.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49)

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt` line 334 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nst04gu6bWWkO2fmCJC:-Nst04gv-Ux6rt2_7NTR:b-91jsew) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/595fa1bd01ed2647822d3e873bfa8ac80e0d92fb/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L334)):*
> ```Kotlin
>   }
> 
>   @Test
> ```

Let's add a test where a wrong certificate is used and that error message is returned?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt` line 151 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nst978DCF9acJz6Z83H:-Nst978ECXi3ny3IvoWV:b-4xjmfq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/595fa1bd01ed2647822d3e873bfa8ac80e0d92fb/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L151)):*
> ```Kotlin
> 
> /**
>  * Verifies a [RandomSeed] from a DataProvider bypassing from a Duchy.
> ```

Do you mean to say "passed through another Duchy"?



_Code quote:_
```Kotlin
bypassing
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt` line 151 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nst978DCF9acJz6Z83H:-NszVxRcEJ2DtleeeCaM:bu4ozqt) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/595fa1bd01ed2647822d3e873bfa8ac80e0d92fb/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L151)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you mean to say "passed through another Duchy"?
</blockquote></details>

Done.
Thanks!
___
*[`src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt` line 334 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nst04gu6bWWkO2fmCJC:-NszV_Eh7sv0ZGl-Z6HU:b-alxhtd) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/595fa1bd01ed2647822d3e873bfa8ac80e0d92fb/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L334)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Let's add a test where a wrong certificate is used and that error message is returned?
</blockquote></details>

Done.
Added two test when certificate is invalid or signature is invalid.

**Review by ple13 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49)* status: all files reviewed, 4 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt` line 397 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nt206DE2bBetLlw9JlR:-Nt206DE2bBetLlw9JlS:b36qgzu) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/084390a2648f97f6739553bd6179d5ceea2f4429/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L397)):*
> ```Kotlin
>     val exception =
>       assertFailsWith<CertPathValidatorException> {
>         verifyElGamalPublicKey(
> ```

verifyEncryptionPublicKey?
___
*[`src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt` line 320 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nt20pkC4N6nL4bX4nPJ:-Nt20pkC4N6nL4bX4nPK:b-l6uxea) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/084390a2648f97f6739553bd6179d5ceea2f4429/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L320)):*
> ```Kotlin
>     val exception =
>       assertFailsWith<CertPathValidatorException> {
>         verifyElGamalPublicKey(
> ```

Is it verifyRandomSeed?
___
*[`src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt` line 339 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nt20urs-fGUoVoTA9Mo:-Nt20urs-fGUoVoTA9Mp:brhumzt) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/084390a2648f97f6739553bd6179d5ceea2f4429/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L339)):*
> ```Kotlin
> 
>     assertFailsWith<SignatureException> {
>       verifyElGamalPublicKey(
> ```

Same here.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt` line 397 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nt206DE2bBetLlw9JlR:-Nt2yNRE0UF84SvC3RhK:bxq2huw) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/084390a2648f97f6739553bd6179d5ceea2f4429/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L397)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

verifyEncryptionPublicKey?
</blockquote></details>

Done.
Thanks for catching it!
___
*[`src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt` line 320 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nt20pkC4N6nL4bX4nPJ:-Nt2yPHt9gynOZGvLtz2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/084390a2648f97f6739553bd6179d5ceea2f4429/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L320)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Is it verifyRandomSeed?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt` line 339 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49#-Nt20urs-fGUoVoTA9Mo:-Nt2yPj6838lkovHrluv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/084390a2648f97f6739553bd6179d5ceea2f4429/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L339)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13)

**Review by ple13 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 2 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/49)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
