### PR TITLE
Minor updates to make the library usable in the cmms correctness test.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11)

### CODE REVIEW

**Review by corbantek — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/BUILD.bazel, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11#-MgI4yTN7lKF5NZAAJdr:-MgI4yTN7lKF5NZAAJds:b-x4orb5) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d99b2af9876871a977aad04027aaea5d304bd4b/src/main/kotlin/org/wfanet/measurement/consent/client/BUILD.bazel#L0)):*
I'm okay with breaking out the client BUILD file into each sub-directory, but is their motivation for this?
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel, line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11#-MgI4_L135fRH1q2G6lZ:-MgI4_L2EFjLEvyF4Cti:bby4gdr) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d99b2af9876871a977aad04027aaea5d304bd4b/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel#L3)):*
> ```Starlark
> load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")
> 
> package(default_visibility = ["//visibility:public"])
> ```

For my own knowledge, does this need to be public so external clients can instantiate the Cryptors?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel, line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11#-MgI4_L135fRH1q2G6lZ:-MgI65JCC-aWKTnc3WCm:b-bkrtr8) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d99b2af9876871a977aad04027aaea5d304bd4b/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel#L3)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

For my own knowledge, does this need to be public so external clients can instantiate the Cryptors?
</blockquote></details>

yep, the client needs to define and pass in a hybridCryptor in order to call the library methods, e.g., in
```
suspend fun createParticipationSignature(
  hybridCryptor: HybridCryptor,    <--- here
  requisition: Requisition,
  privateKeyHandle: PrivateKeyHandle,
  dataProviderX509: ByteString
)
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11#-MgI4yTN7lKF5NZAAJdr:-MgI7I2w2cdZXpFhWZll:bbehtw6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d99b2af9876871a977aad04027aaea5d304bd4b/src/main/kotlin/org/wfanet/measurement/consent/client/BUILD.bazel#L)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

I'm okay with breaking out the client BUILD file into each sub-directory, but is their motivation for this?
</blockquote></details>

Well, I couldn't find any bazel best practice online suggesting this. But so far I always see BUILD file stays in the same directory with the code files.

I was confused a little bit since I didn't find BUILD file in the sub-directory, and I thought they were not used anywhere.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11#-MgI4yTN7lKF5NZAAJdr:-MgI94Y86prJ5VVXWdch:b4ffce0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d99b2af9876871a977aad04027aaea5d304bd4b/src/main/kotlin/org/wfanet/measurement/consent/client/BUILD.bazel#L)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Well, I couldn't find any bazel best practice online suggesting this. But so far I always see BUILD file stays in the same directory with the code files.

I was confused a little bit since I didn't find BUILD file in the sub-directory, and I thought they were not used anywhere.
</blockquote></details>

ok, I find one online

`If a BUILD file refers to files in subdirectories (such as, srcs = ["a/b/C.java"]) it’s a sign that a BUILD file should be added to that subdirectory.`

https://docs.bazel.build/versions/main/best-practices.html#packages

**Review by corbantek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11#-MgIUPLIAzuzV7ydeOb2:-MgIUPLIAzuzV7ydeOb3:btuo567) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/77d1856379162871964f07b6daebc5e86848d5ea/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L68)):*
> ```
> createEncryptionPublicKeySignature
> ```
To be consistent with a similar method in DuchyClient, this should be `signEncryptionPublicKey`.

There's an argument for splitting up `createParticipationSignature` into `buildRequisitionFingerprint` and `signRequisitionFingerprint` if we really want everything that signs messages to be prefixed with `sign`, but that can be handled in a separate PR if we decide it's important.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/BUILD.bazel, line 6 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11#-MgIW7f173yi_C4i20P0:-MgIW7f2D26AMU1oz0l4:b-m13kko) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/77d1856379162871964f07b6daebc5e86848d5ea/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/BUILD.bazel#L6)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "duchy",
> ```

Any particular reason for splitting this into multiple packages, as opposed to just multiple targets within a single package (given that each one will likely have a single source file)?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11#-MgIWMdK1qAuOfRJs2ie:-MgIWMdK1qAuOfRJs2if:b-ir69nw) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/77d1856379162871964f07b6daebc5e86848d5ea/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L25)):*
> ```
> createEncryptionPublicKeySignature
> ```
Same here re: "sign"

**Review by corbantek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @corbantek, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/BUILD.bazel, line 6 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11#-MgIW7f173yi_C4i20P0:-MgIvyo55sTfv5GSh5n5:b-e4j6b5) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/77d1856379162871964f07b6daebc5e86848d5ea/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/BUILD.bazel#L6)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

We already have multiple packages since these clients are in different subdirectories. But we only have a single BUILD target for them.

I split the build target since https://docs.bazel.build/versions/main/best-practices.html#packages says
"If a BUILD file refers to files in subdirectories (such as, srcs = ["a/b/C.java"]) it’s a sign that a BUILD file should be added to that subdirectory."

Moving all files into the same directory won't work, since we have multiple functions with the same name and parameters, e.g, signPublicEncryptionKey()
</blockquote></details>

I agree with Yao, since these are all classless functions, its nice to keep the package/"namespace" of these functions under their respective package for the client

**Review by corbantek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/11)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @corbantek, @SanjayVas, @stevenwarejones, and @wangyaopw)

**Pull request merged**
