### PR TITLE
Import wfa_common_jvm.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[WORKSPACE, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5#-Megx1hD3AEO8sIH6z1T:-Megx1hD3AEO8sIH6z1U:b-ymm348) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2c6cca73af7b3646d995f384288bbf1151584e90/WORKSPACE#L27)):*
> ```Starlark
> # Measurement system.
> http_archive(
>     name = "wfa_common_jvm",
> ```

add in the hash please.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[WORKSPACE, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5#-MegzWUD9-LcRjEIS2Ke:-MegzWUD9-LcRjEIS2Kf:bbu9c17) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e08ab8433ed0b5103b3a46b3f119c7d109e94b36/WORKSPACE#L45)):*
> ```Starlark
> load("//build/com_google_truth:repo.bzl", "com_google_truth_artifact_dict")
> 
> # Measurement system.
> ```

This is needed for the computation and requisition protos isn't it?
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6926ac10bb4cd9b1ff678b91b9258fce3791ef19/src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel#L10

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[WORKSPACE, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5#-Megx1hD3AEO8sIH6z1T:-Mek2FlA3j1wmd1uALiG:bcjgyd4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2c6cca73af7b3646d995f384288bbf1151584e90/WORKSPACE#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

add in the hash please.
</blockquote></details>

Done.

Oops, good catch.
___
*[WORKSPACE, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5#-MegzWUD9-LcRjEIS2Ke:-Mek2Pjv56MOz6Z8MX2I:b-izwkc6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/e08ab8433ed0b5103b3a46b3f119c7d109e94b36/WORKSPACE#L45)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This is needed for the computation and requisition protos isn't it?
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6926ac10bb4cd9b1ff678b91b9258fce3791ef19/src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel#L10
</blockquote></details>

We don't want any other repo to depend on cross-media-measurement. I thought this client was only going to be for the public API, not the system one. I should have noticed that #4 was referencing them.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
